<script setup>
import { ref, onMounted } from "vue";
import Navbar from "../components/Navbar.vue/Navbar.vue";
import { useUserStore } from "../stores/userStore";
import api from "../services/api";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const user = useUserStore();

const projects = ref([]);
const skills = ref([]);

const certificates = ref([]);


async function loadProjects() {
  try {
    const response = await api.get("/projects");
    projects.value = response.data;
  } catch (error) {
    console.error(error);
  }
}




async function loadSkills() {
  try {
    const response = await api.get("/skills");
    skills.value = response.data;
  } catch (error) {
    console.error(error);
  }
}

async function loadCertificates() {
  try {
    const response = await api.get("/certificates");
    certificates.value = response.data;
  } catch (error) {
    console.error(error);
  }
}


async function downloadResume() {
  const resume = document.querySelector(".resume-container");

  const canvas = await html2canvas(resume);
  const imgData = canvas.toDataURL("image/png");

  const pdf = new jsPDF("p", "mm", "a4");

  const width = pdf.internal.pageSize.getWidth();
  const height = (canvas.height * width) / canvas.width;

  pdf.addImage(imgData, "PNG", 0, 0, width, height);

  pdf.save("Resume.pdf");
}

onMounted(() => {
  loadProjects();
  loadSkills();
  loadCertificates();
});
</script>

<template>
  <Navbar />

  <div class="resume-container">

    <div class="resume-header">
      <div class="avatar">
        {{ user.name.charAt(0) }}
      </div>

      <h1>{{ user.name }}</h1>

      <p class="role">{{ user.role }}</p>

      <div class="contact">
        <span>📧 {{ user.email }}</span>
        <span>📍 {{ user.city }}</span>
        <span>🎓 {{ user.university }}</span>
      </div>
    </div>

    <div class="section">
      <h2>👤 Personal Information</h2>

      <p><strong>Name:</strong> {{ user.name }}</p>
      <p><strong>Email:</strong> {{ user.email }}</p>
      <p><strong>City:</strong> {{ user.city }}</p>
      <p><strong>Role:</strong> {{ user.role }}</p>
      <p><strong>University:</strong> {{ user.university }}</p>

      <p>
        <strong>GitHub:</strong>
        <a :href="user.github" target="_blank">
          {{ user.github }}
        </a>
      </p>
    </div>

    <div class="section">
      <h2>💻 Skills</h2>

      <ul v-if="skills.length">
  <li v-for="skill in skills" :key="skill._id">
    {{ skill.name }}
  </li>
</ul>

<p v-else>No skills added yet.</p>

    </div>

        <div class="section">
      <h2>📁 Projects</h2>

      <ul v-if="projects.length">
        <li v-for="project in projects" :key="project._id">
          <strong>{{ project.title }}</strong><br>
          {{ project.description }}
        </li>
      </ul>

      <p v-else>No projects added yet.</p>
    </div>

    <div class="section">
  <h2>🏆 Certificates</h2>

  <ul v-if="certificates.length">
    <li v-for="certificate in certificates" :key="certificate._id">
      <strong>{{ certificate.name }}</strong><br>
      {{ certificate.provider }}
    </li>
  </ul>

  <p v-else>No certificates added yet.</p>
</div>
    <button class="download-btn" @click="downloadResume">
      Download Resume
    </button>

    <div class="resume-footer">
      <p>Generated by CareerBridge</p>
    </div>

  </div>
</template>

<style scoped>
.resume-container{
  max-width:800px;
  margin:40px auto;
  background:#fff;
  padding:30px;
  border-radius:15px;
  box-shadow:0 8px 20px rgba(0,0,0,.1);
}

h1{
  text-align:center;
  color:#2563eb;
  margin-bottom:30px;
}

.section{
  background:#f8fafc;
  border-left:5px solid #2563eb;
  border-radius:12px;
  padding:22px;
  margin-bottom:25px;
}

.section ul{
  list-style:none;
  padding:0;
}

.section li{
  background:white;
  padding:12px 15px;
  border-radius:10px;
  margin-bottom:10px;
  box-shadow:0 4px 10px rgba(0,0,0,.05);
}

.section h2{
  color:#2563eb;
  margin-bottom:10px;
}

.section h2::after{
  content:"";
  display:block;
  width:60px;
  height:3px;
  background:#2563eb;
  margin-top:8px;
  border-radius:10px;
}

.download-btn{
  width:100%;
  padding:16px;
  background:linear-gradient(135deg,#2563eb,#1d4ed8);
  color:white;
  border:none;
  border-radius:12px;
  font-size:17px;
  font-weight:bold;
  cursor:pointer;
  transition:.3s;
}

.download-btn:hover{
  transform:translateY(-2px);
  box-shadow:0 10px 20px rgba(37,99,235,.25);
}

.resume-header{
  text-align:center;
  border-bottom:2px solid #e5e7eb;
  padding-bottom:30px;
  margin-bottom:35px;
}

.avatar{
  width:90px;
  height:90px;
  margin:auto;
  border-radius:50%;
  background:#2563eb;
  color:white;
  display:flex;
  justify-content:center;
  align-items:center;
  font-size:40px;
  font-weight:bold;
  margin-bottom:15px;
}

.role{
  color:#2563eb;
  font-size:20px;
  font-weight:bold;
  margin:10px 0 20px;
}

.contact{
  display:flex;
  justify-content:center;
  gap:25px;
  flex-wrap:wrap;
  color:#475569;
  font-size:15px;
}

.resume-footer{
  margin-top:40px;
  padding-top:20px;
  border-top:1px solid #e5e7eb;
  text-align:center;
  color:#64748b;
  font-size:14px;
}
</style>